// Code generated by tools/jsxbuild from Boot.jsx. DO NOT EDIT.
var __defProp = Object.defineProperty;
var __defProps = Object.defineProperties;
var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
(function() {
  const { useState, useEffect, useCallback } = React;
  const NAV_IDS = (window.NAV || []).filter((i) => !i.section).map((i) => i.id);
  const ROUTES = [
    { id: "chat", path: "/", title: "geoffmiller.cloud \u2014 Ask my r\xE9sum\xE9 anything" },
    { id: "resume", path: "/resume", title: "R\xE9sum\xE9 \u2014 Geoffrey Miller" },
    { id: "projects", path: "/projects", title: "Projects \u2014 Geoffrey Miller" },
    { id: "achievements", path: "/achievements", title: "Achievements \u2014 Geoffrey Miller", feature: "achievements" },
    { id: "recommendations", path: "/recommendations", title: "Recommendations \u2014 Geoffrey Miller" },
    { id: "articles", path: "/articles", title: "Articles \u2014 Geoffrey Miller" },
    { id: "resources", path: "/resources", title: "Resources \u2014 Geoffrey Miller", feature: "resources" },
    { id: "about", path: "/about", title: "About Geoff \u2014 Geoffrey Miller" },
    { id: "contact", path: "/contact", title: "Contact \u2014 Geoffrey Miller" }
  ];
  const dlPayload = (o) => {
    const out = {};
    Object.keys(o).forEach((k) => {
      if (o[k]) out[k] = o[k];
    });
    return Object.keys(out).length ? out : null;
  };
  const PARAM_TO_DEEPLINK = {
    resume: (p) => dlPayload({ roleId: p.role }),
    projects: (p) => dlPayload({ projectId: p.project, subpageId: p.subpage, categoryId: p.category }),
    achievements: (p) => dlPayload({ achievementId: p.achievement }),
    articles: (p) => dlPayload({ articleId: p.article, seriesId: p.series }),
    recommendations: (p) => dlPayload({ recId: p.rec })
  };
  const DEEPLINK_TO_PARAM = {
    resume: (d) => d ? { role: d.roleId } : {},
    projects: (d) => d ? { project: d.projectId, subpage: d.subpageId, category: d.categoryId } : {},
    achievements: (d) => d ? { achievement: d.achievementId } : {},
    articles: (d) => d ? { article: d.articleId, series: d.seriesId } : {},
    recommendations: (d) => d ? { rec: d.recId } : {}
  };
  const ENABLED_ROUTES = ROUTES.filter((r) => (window.featureOn || (() => true))(r.feature));
  const router = AppKitRouter.create({ routes: ENABLED_ROUTES, notFound: "chat" });
  const readDeepLink = (state) => {
    const toDL = PARAM_TO_DEEPLINK[state.id];
    window.DEEP_LINK = toDL ? toDL(state.params) : null;
    return window.DEEP_LINK;
  };
  readDeepLink(router.current());
  const App = () => {
    const [route, setRouteState] = useState(() => router.current().id);
    const [deepNonce, setDeepNonce] = useState(0);
    const deepSigRef = useRef("");
    const routeRef = React.useRef(router.current().id);
    const bootedRef = React.useRef(false);
    const [paletteOpen, setPaletteOpen] = useState(false);
    const [tweaksVisible, setTweaksVisible] = useState(false);
    const [sidebarOpen, setSidebarOpen] = useState(false);
    const [prefs, setPrefs] = useState(() => {
      try {
        const saved = JSON.parse(localStorage.getItem("prefs") || "null");
        return saved || window.TWEAK_DEFAULTS;
      } catch (e) {
        return window.TWEAK_DEFAULTS;
      }
    });
    useEffect(() => {
      const root = document.documentElement;
      root.setAttribute("data-theme", prefs.theme);
      root.setAttribute("data-aesthetic", prefs.aesthetic);
      root.setAttribute("data-accent", prefs.accent);
      root.setAttribute("data-density", prefs.density);
      root.setAttribute("data-grid", prefs.grid);
      localStorage.setItem("prefs", JSON.stringify(prefs));
    }, [prefs]);
    useEffect(() => {
      const off = router.onChange((state) => {
        const dl = readDeepLink(state);
        const sig = dl ? JSON.stringify(dl) : "";
        if (bootedRef.current && routeRef.current === state.id && sig !== deepSigRef.current) {
          setDeepNonce((n) => n + 1);
        }
        deepSigRef.current = sig;
        bootedRef.current = true;
        routeRef.current = state.id;
        setRouteState(state.id);
      });
      window.ROUTE_SET = (id) => router.navigate(id);
      window.GO = (id, payload) => router.navigate(id, { params: DEEPLINK_TO_PARAM[id] ? DEEPLINK_TO_PARAM[id](payload) : {} });
      router.start();
      return off;
    }, []);
    useEffect(() => {
      const onKey = (e) => {
        const mod = e.metaKey || e.ctrlKey;
        if (mod && e.key.toLowerCase() === "k") {
          e.preventDefault();
          setPaletteOpen((o) => !o);
          return;
        }
        if (mod && "12345678".includes(e.key)) {
          e.preventDefault();
          router.navigate(NAV_IDS[parseInt(e.key, 10) - 1]);
        }
        if (e.key === "Escape") {
          setPaletteOpen(false);
        }
      };
      window.addEventListener("keydown", onKey);
      return () => window.removeEventListener("keydown", onKey);
    }, []);
    useEffect(() => {
      var _a;
      const onMsg = (e) => {
        var _a2, _b;
        if (((_a2 = e.data) == null ? void 0 : _a2.type) === "__activate_edit_mode") setTweaksVisible(true);
        if (((_b = e.data) == null ? void 0 : _b.type) === "__deactivate_edit_mode") setTweaksVisible(false);
      };
      window.addEventListener("message", onMsg);
      (_a = window.parent) == null ? void 0 : _a.postMessage({ type: "__edit_mode_available" }, "*");
      return () => window.removeEventListener("message", onMsg);
    }, []);
    const toggleTheme = () => setPrefs((p) => __spreadProps(__spreadValues({}, p), { theme: p.theme === "dark" ? "light" : "dark" }));
    const setRoute = (id) => router.navigate(id);
    const Page = {
      chat: window.ChatPage,
      resume: window.ResumePage,
      projects: window.ProjectsPage,
      recommendations: window.RecommendationsPage,
      articles: window.ArticlesPage,
      resources: window.ResourcesPage,
      achievements: window.AchievementsPage,
      about: window.AboutPage,
      contact: window.ContactPage
    }[route] || window.ChatPage;
    return /* @__PURE__ */ React.createElement("div", { className: "app", "data-screen-label": "page \xB7 " + route }, /* @__PURE__ */ React.createElement(
      Sidebar,
      {
        route,
        setRoute,
        onOpenPalette: () => setPaletteOpen(true),
        sidebarOpen,
        setSidebarOpen
      }
    ), /* @__PURE__ */ React.createElement("div", { className: "main-column" }, /* @__PURE__ */ React.createElement(
      HeaderBar,
      {
        theme: prefs.theme,
        onToggleTheme: toggleTheme,
        onOpenPalette: () => setPaletteOpen(true),
        onToggleMobile: () => setSidebarOpen((o) => !o)
      }
    ), /* @__PURE__ */ React.createElement(Page, { key: route + "#" + deepNonce })), route !== "chat" && window.ChatRail && /* @__PURE__ */ React.createElement(ChatRail, null), /* @__PURE__ */ React.createElement(CommandPalette, { open: paletteOpen, onClose: () => setPaletteOpen(false), setRoute }), /* @__PURE__ */ React.createElement(TweaksPanel, { visible: tweaksVisible, prefs, setPrefs }));
  };
  const tryRender = () => {
    if (!window.ChatPage || !window.ResumePage || !window.ProjectsPage || !window.ArticlesPage || !window.ResourcesPage || !window.AchievementsPage || !window.AboutPage || !window.ContactPage || !window.RecommendationsPage || !window.Sidebar || !window.CommandPalette || !window.TweaksPanel || !window.Icon) {
      setTimeout(tryRender, 30);
      return;
    }
    ReactDOM.createRoot(document.getElementById("root")).render(/* @__PURE__ */ React.createElement(App, null));
  };
  tryRender();
})();
