// Code generated by tools/jsxbuild from ChatAgent.jsx. DO NOT EDIT.
const CHAT_ENDPOINT_URL = window.CHAT_ENDPOINT || "https://juybni0ik4.execute-api.us-east-1.amazonaws.com/";
const CHAT_FALLBACK = "Sorry, I couldn't answer that one \u2014 try rephrasing.";
const CHAT_UNREACHABLE = "I couldn't reach the agent just now \u2014 please try again in a moment.";
async function askAgent(question, persona) {
  const q = String(question || "").trim();
  if (!q) return { answer: "", blocked: false };
  try {
    const res = await fetch(CHAT_ENDPOINT_URL, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        question: q,
        persona: persona || localStorage.getItem("persona") || "ai"
      })
    });
    const data = await res.json().catch(() => ({}));
    return {
      answer: data.answer || CHAT_FALLBACK,
      blocked: data.blocked === true
    };
  } catch (err) {
    return { answer: CHAT_UNREACHABLE, blocked: false, failed: true };
  }
}
window.CHAT_ENDPOINT_URL = CHAT_ENDPOINT_URL;
window.askAgent = askAgent;
