// Code generated by tools/jsxbuild from ChatRail.jsx. DO NOT EDIT.
const CHAT_RAIL_BREAKPOINT = 1600;
const ChatRail = () => {
  const [docked, setDocked] = useState(() => window.innerWidth >= CHAT_RAIL_BREAKPOINT);
  const [open, setOpen] = useState(false);
  const [turns, setTurns] = useState([]);
  const [pending, setPending] = useState(false);
  const [input, setInput] = useState("");
  const inputRef = useRef(null);
  const logRef = useRef(null);
  useEffect(() => {
    const mq = window.matchMedia("(min-width: " + CHAT_RAIL_BREAKPOINT + "px)");
    const sync = () => setDocked(mq.matches);
    sync();
    mq.addEventListener ? mq.addEventListener("change", sync) : mq.addListener(sync);
    return () => mq.removeEventListener ? mq.removeEventListener("change", sync) : mq.removeListener(sync);
  }, []);
  useEffect(() => {
    var _a, _b;
    (_b = (_a = logRef.current) == null ? void 0 : _a.scrollTo) == null ? void 0 : _b.call(_a, { top: 999999, behavior: "smooth" });
  }, [turns, pending]);
  const shownRecs = useRef([]);
  const shownEnts = useRef([]);
  const send = async (raw) => {
    const q = String(raw || "").trim();
    if (!q || pending) return;
    setTurns((t) => [...t, { role: "user", content: q }]);
    setInput("");
    setPending(true);
    const { answer, blocked, failed } = await window.askAgent(q);
    const quiet = blocked || failed;
    const hits = quiet || !window.recommendationsFor ? [] : window.recommendationsFor(q, { exclude: shownRecs.current });
    hits.forEach((h) => shownRecs.current.push(h.rec.id));
    const ents = quiet || !window.entitiesFor ? [] : window.entitiesFor(q, { exclude: shownEnts.current });
    ents.forEach((e) => shownEnts.current.push(e.kind + ":" + e.id));
    setTurns((t) => [...t, { role: "assistant", content: answer, recs: hits, ents }]);
    setPending(false);
  };
  useEffect(() => {
    window.ASK = (seed) => {
      if (!docked) setOpen(true);
      setInput(String(seed || ""));
      setTimeout(() => {
        var _a, _b, _c;
        (_a = inputRef.current) == null ? void 0 : _a.focus();
        (_c = (_b = inputRef.current) == null ? void 0 : _b.setSelectionRange) == null ? void 0 : _c.call(_b, 999, 999);
      }, 60);
    };
    return () => {
      delete window.ASK;
    };
  }, [docked]);
  useEffect(() => {
    if (docked || !open) return void 0;
    const onKey = (ev) => {
      if (ev.key === "Escape") setOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [docked, open]);
  const panel = /* @__PURE__ */ React.createElement("div", { className: "chatrail-panel" }, /* @__PURE__ */ React.createElement("div", { className: "chatrail-head" }, /* @__PURE__ */ React.createElement(Icon, { name: "sparkles", size: 13 }), /* @__PURE__ */ React.createElement("span", { className: "chatrail-title" }, "Ask about Geoff"), /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      className: "chatrail-full",
      onClick: () => {
        var _a;
        (_a = window.ROUTE_SET) == null ? void 0 : _a.call(window, "chat");
        setOpen(false);
      }
    },
    "Full chat"
  ), !docked && /* @__PURE__ */ React.createElement("button", { type: "button", className: "chatrail-x", "aria-label": "Close", onClick: () => setOpen(false) }, "\xD7")), /* @__PURE__ */ React.createElement("div", { className: "chatrail-log", ref: logRef }, turns.length === 0 && !pending && /* @__PURE__ */ React.createElement("div", { className: "chatrail-empty" }, /* @__PURE__ */ React.createElement("p", null, "Ask anything about Geoff's background \u2014 it answers from his r\xE9sum\xE9, not from guesswork."), /* @__PURE__ */ React.createElement("div", { className: "chatrail-seeds" }, [
    "Does he fit a Principal Cloud Architect role?",
    "What's his agentic AI experience?",
    "Show me his FinOps results."
  ].map((s) => /* @__PURE__ */ React.createElement("button", { key: s, type: "button", className: "chatrail-seed", onClick: () => send(s) }, s)))), turns.map((t, i) => /* @__PURE__ */ React.createElement("div", { key: i, className: "chatrail-turn is-" + t.role }, t.content, (t.ents || []).length > 0 && window.EntityCards && /* @__PURE__ */ React.createElement(window.EntityCards, { entities: t.ents }), (t.recs || []).length > 0 && window.RecommendationQuote && /* @__PURE__ */ React.createElement("div", { className: "chatrail-recs" }, t.recs.map((h) => /* @__PURE__ */ React.createElement(window.RecommendationQuote, { key: h.rec.id, hit: h }))))), pending && /* @__PURE__ */ React.createElement("div", { className: "chatrail-turn is-assistant chatrail-pending" }, "Thinking\u2026")), /* @__PURE__ */ React.createElement("form", { className: "chatrail-form", onSubmit: (e) => {
    e.preventDefault();
    send(input);
  } }, /* @__PURE__ */ React.createElement(
    "input",
    {
      ref: inputRef,
      className: "chatrail-input",
      value: input,
      onChange: (e) => setInput(e.target.value),
      placeholder: "Ask about a role, a project, a number\u2026",
      "aria-label": "Ask about Geoff"
    }
  ), /* @__PURE__ */ React.createElement("button", { type: "submit", className: "chatrail-send", disabled: !input.trim() || pending, "aria-label": "Send" }, /* @__PURE__ */ React.createElement(Icon, { name: "send", size: 13 }))));
  if (docked) return /* @__PURE__ */ React.createElement("aside", { className: "chatrail is-docked" }, panel);
  return /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      className: "chatrail-fab" + (open ? " is-open" : ""),
      "aria-label": "Ask about Geoff",
      "aria-expanded": open,
      onClick: () => setOpen((o) => !o)
    },
    /* @__PURE__ */ React.createElement(Icon, { name: "sparkles", size: 16 })
  ), open && /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("div", { className: "chatrail-scrim", onClick: () => setOpen(false) }), /* @__PURE__ */ React.createElement("aside", { className: "chatrail is-drawer" }, panel)));
};
window.ChatRail = ChatRail;
window.CHAT_RAIL_BREAKPOINT = CHAT_RAIL_BREAKPOINT;
