// Code generated by tools/jsxbuild from CommandPalette.jsx. DO NOT EDIT.
const _cpEnabled = (id) => (window.NAV || []).filter((i) => !i.section).some((i) => i.id === id);
const { useState: _cpUseState, useEffect: _cpUseEffect, useRef: _cpUseRef, useMemo: _cpUseMemo } = React;
const CommandPalette = ({ open, onClose, setRoute }) => {
  const [q, setQ] = React.useState("");
  const [idx, setIdx] = React.useState(0);
  const inputRef = React.useRef(null);
  const D = window.SITE_DATA;
  React.useEffect(() => {
    if (open) {
      setQ("");
      setIdx(0);
      setTimeout(() => {
        var _a;
        return (_a = inputRef.current) == null ? void 0 : _a.focus();
      }, 10);
    }
  }, [open]);
  const items = React.useMemo(() => {
    var _a;
    const base = [
      { kind: "Nav", id: "chat", title: "JD Chat", sub: "Recruiter-friendly chat with my background", icon: "sparkles", go: () => setRoute("chat") },
      { kind: "Nav", id: "resume", title: "Interactive Resume", sub: "Persona toggle, impact dashboards", icon: "file", go: () => setRoute("resume") },
      { kind: "Nav", id: "projects", title: "Projects", sub: "Professional, OSS, and closed source", icon: "folder", go: () => setRoute("projects") },
      { kind: "Nav", id: "achievements", title: "Achievements", sub: "A number, a story, and a stack", icon: "award", go: () => setRoute("achievements") },
      { kind: "Nav", id: "articles", title: "Articles", sub: "Blog and engineering guides", icon: "book", go: () => setRoute("articles") },
      { kind: "Nav", id: "resources", title: "Resources", sub: "What I read, watch, listen to", icon: "layers", go: () => setRoute("resources") },
      { kind: "Nav", id: "about", title: "About Geoff", sub: "Dad, BJJ, Latin dance, tinkering", icon: "user", go: () => setRoute("about") },
      { kind: "Nav", id: "contact", title: "Contact", sub: "Let's connect", icon: "mail", go: () => setRoute("contact") }
    ].filter((e) => _cpEnabled(e.id));
    const articles = D.articles.map((a) => ({ kind: "Article", id: a.id, title: a.title, sub: a.tags.join(" \xB7 "), icon: "book", go: () => {
      var _a2;
      return (_a2 = window.GO) == null ? void 0 : _a2.call(window, "articles", { articleId: a.id });
    } }));
    const projects = D.projects.map((a) => ({ kind: "Project", id: a.id, title: a.title, sub: a.org + " \xB7 " + a.year, icon: "folder", go: () => {
      var _a2;
      return (_a2 = window.GO) == null ? void 0 : _a2.call(window, "projects", { projectId: a.id });
    } }));
    const roles = D.roles.map((r) => ({ kind: "Role", id: r.id, title: r.title + " \xB7 " + r.company, sub: r.start + " \u2013 " + r.end, icon: "file", go: () => {
      var _a2;
      return (_a2 = window.GO) == null ? void 0 : _a2.call(window, "resume", { roleId: r.id });
    } }));
    const series = (D.series || []).map((s) => {
      const parts = D.articles.filter((a) => a.series && (a.series.ref === s.id || a.series.name === s.title)).length;
      return {
        kind: "Series",
        id: s.id,
        title: s.title,
        sub: s.dek || parts + " part" + (parts === 1 ? "" : "s"),
        icon: "layers",
        go: () => {
          var _a2;
          return (_a2 = window.GO) == null ? void 0 : _a2.call(window, "articles", { seriesId: s.id });
        }
      };
    });
    const subpages = D.projects.reduce((acc, p) => {
      (p.subpages || []).forEach((sp) => acc.push({
        kind: "Project page",
        id: p.id + "/" + sp.id,
        title: p.title + " \xB7 " + (sp.title || sp.id),
        sub: p.org,
        icon: "list",
        go: () => {
          var _a2;
          return (_a2 = window.GO) == null ? void 0 : _a2.call(window, "projects", { projectId: p.id, subpageId: sp.id });
        }
      }));
      return acc;
    }, []);
    const actions = [
      { kind: "Action", id: "download", title: "Download PDF resume", sub: "Static, recruiter-ready", icon: "download", go: () => window.print() },
      ...((_a = window.featureOn) == null ? void 0 : _a.call(window, "contactDetails")) !== false ? [{ kind: "Action", id: "copyemail", title: "Copy email", sub: D.profile.email, icon: "mail", go: () => {
        var _a2;
        return (_a2 = navigator.clipboard) == null ? void 0 : _a2.writeText(D.profile.email);
      } }] : [{ kind: "Action", id: "linkedin", title: "Message me on LinkedIn", sub: D.profile.links.linkedin, icon: "mail", go: () => window.open("https://" + D.profile.links.linkedin, "_blank", "noopener,noreferrer") }]
    ];
    const all = [...base, ...roles, ...projects, ...subpages, ...series, ...articles, ...actions];
    if (!q.trim()) return all;
    const needle = q.toLowerCase();
    return all.filter((it) => (it.title + " " + it.sub + " " + it.kind).toLowerCase().includes(needle));
  }, [q, setRoute]);
  React.useEffect(() => {
    setIdx(0);
  }, [q]);
  const run = (it) => {
    it.go();
    onClose();
  };
  const onKey = (e) => {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setIdx((i) => Math.min(items.length - 1, i + 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setIdx((i) => Math.max(0, i - 1));
    } else if (e.key === "Enter") {
      e.preventDefault();
      if (items[idx]) run(items[idx]);
    } else if (e.key === "Escape") {
      onClose();
    }
  };
  if (!open) return null;
  const groups = items.reduce((acc, it) => {
    var _a;
    (acc[_a = it.kind] || (acc[_a] = [])).push(it);
    return acc;
  }, {});
  return /* @__PURE__ */ React.createElement("div", { className: "cmdk-backdrop", onClick: onClose }, /* @__PURE__ */ React.createElement("div", { className: "cmdk-panel panel", onClick: (e) => e.stopPropagation() }, /* @__PURE__ */ React.createElement("div", { className: "cmdk-input-row" }, /* @__PURE__ */ React.createElement(Icon, { name: "search", size: 16, style: { color: "var(--text-mute)" } }), /* @__PURE__ */ React.createElement(
    "input",
    {
      ref: inputRef,
      placeholder: "Search pages, roles, projects, articles\u2026",
      value: q,
      onChange: (e) => setQ(e.target.value),
      onKeyDown: onKey
    }
  ), /* @__PURE__ */ React.createElement("span", { className: "kbd" }, "ESC")), /* @__PURE__ */ React.createElement("div", { className: "cmdk-results" }, Object.keys(groups).length === 0 && /* @__PURE__ */ React.createElement("div", { className: "cmdk-empty" }, 'No results for "', q, '"'), Object.entries(groups).map(([group, list]) => /* @__PURE__ */ React.createElement("div", { key: group, className: "cmdk-group" }, /* @__PURE__ */ React.createElement("div", { className: "cmdk-group-label" }, group), list.map((it) => {
    const flatIdx = items.indexOf(it);
    const active = flatIdx === idx;
    return /* @__PURE__ */ React.createElement(
      "div",
      {
        key: group + "-" + it.id,
        className: "cmdk-item" + (active ? " active" : ""),
        onMouseEnter: () => setIdx(flatIdx),
        onClick: () => run(it)
      },
      /* @__PURE__ */ React.createElement(Icon, { name: it.icon, size: 14, style: { color: active ? "var(--accent)" : "var(--text-mute)" } }),
      /* @__PURE__ */ React.createElement("div", { className: "grow", style: { minWidth: 0 } }, /* @__PURE__ */ React.createElement("div", { className: "cmdk-title" }, it.title), /* @__PURE__ */ React.createElement("div", { className: "cmdk-sub" }, it.sub)),
      active && /* @__PURE__ */ React.createElement(Icon, { name: "arrow", size: 14, style: { color: "var(--accent)" } })
    );
  })))), /* @__PURE__ */ React.createElement("div", { className: "cmdk-foot" }, /* @__PURE__ */ React.createElement("span", null, /* @__PURE__ */ React.createElement("span", { className: "kbd" }, "\u2191\u2193"), " navigate"), /* @__PURE__ */ React.createElement("span", null, /* @__PURE__ */ React.createElement("span", { className: "kbd" }, "\u21B5"), " select"), /* @__PURE__ */ React.createElement("span", null, /* @__PURE__ */ React.createElement("span", { className: "kbd" }, "\u2318K"), " close"), /* @__PURE__ */ React.createElement("span", { className: "grow" }), /* @__PURE__ */ React.createElement("span", { style: { color: "var(--text-faint)" } }, items.length, " result", items.length === 1 ? "" : "s"))));
};
window.CommandPalette = CommandPalette;
