// Code generated by tools/jsxbuild from Recommendations.jsx. DO NOT EDIT.
const REL_LABEL = {
  "managed-geoff": "His manager",
  "reported-to-geoff": "Reported to Geoff",
  "senior-to-geoff": "Senior to Geoff",
  "geoff-senior": "Geoff was senior",
  "same-team": "Same team",
  "different-teams": "Different team",
  "different-company": "Different company"
};
const REL_TONE = {
  "managed-geoff": "amber",
  "reported-to-geoff": "cyan",
  "senior-to-geoff": "amber",
  "different-company": "purple"
};
const THEME_LABEL = {
  leadership: "Leadership",
  mentoring: "Mentoring",
  platform: "Platform / K8s",
  "cloud-architecture": "Cloud architecture",
  finops: "FinOps",
  iac: "IaC",
  ai: "AI & agentic",
  communication: "Communication",
  stakeholder: "Stakeholders",
  collaboration: "Collaboration",
  delivery: "Delivery",
  innovation: "Innovation",
  "problem-solving": "Problem solving"
};
const PERSON_TONES = ["var(--neon-pink)", "var(--neon-cyan)", "var(--neon-amber)", "var(--neon-purple)", "var(--neon-blue)"];
const Avatar = ({ person, size = 48 }) => {
  const [failed, setFailed] = React.useState(false);
  const initials = String(person.name || "").split(/\s+/).filter(Boolean).slice(0, 2).map((w) => w[0]).join("").toUpperCase();
  let h = 0;
  for (let i = 0; i < person.name.length; i++) h = h * 31 + person.name.charCodeAt(i) >>> 0;
  const tone = PERSON_TONES[h % PERSON_TONES.length];
  if (person.avatar && !failed) {
    return /* @__PURE__ */ React.createElement(
      "img",
      {
        className: "rec-avatar",
        src: "assets/people/" + person.avatar,
        alt: "",
        width: size,
        height: size,
        loading: "lazy",
        onError: () => setFailed(true)
      }
    );
  }
  return /* @__PURE__ */ React.createElement(
    "span",
    {
      className: "rec-avatar rec-avatar-mono",
      "aria-hidden": "true",
      style: {
        width: size,
        height: size,
        color: tone,
        borderColor: tone,
        fontSize: Math.round(size * 0.34)
      }
    },
    initials
  );
};
const OrgMark = ({ org, logo }) => {
  if (logo) return /* @__PURE__ */ React.createElement("img", { className: "rec-orgmark-img", src: "assets/orgs/" + logo, alt: "", loading: "lazy" });
  const initials = String(org || "").replace(/[^A-Za-z0-9 /]/g, " ").split(/[\s/]+/).filter(Boolean).slice(0, 3).map((w) => w[0]).join("").toUpperCase();
  return /* @__PURE__ */ React.createElement("span", { className: "rec-orgmark", "aria-hidden": "true" }, initials);
};
const fmtRecDate = (iso) => {
  const d = /* @__PURE__ */ new Date(iso + "T00:00:00");
  return d.toLocaleDateString("en-US", { month: "short", year: "numeric" });
};
const RecommendationCard = ({ rec, claims, onOpenClaim, onOpen }) => {
  const lead = rec.pullQuotes && rec.pullQuotes[0];
  const openIt = () => onOpen && onOpen(rec.id);
  return /* @__PURE__ */ React.createElement(
    "article",
    {
      className: "rec-card",
      role: "button",
      tabIndex: 0,
      "aria-label": "Read " + rec.author.name + "'s full recommendation",
      onClick: (e) => {
        if (!e.target.closest("a,button")) openIt();
      },
      onKeyDown: (e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          openIt();
        }
      }
    },
    /* @__PURE__ */ React.createElement("header", { className: "rec-head" }, /* @__PURE__ */ React.createElement(Avatar, { person: rec.author }), /* @__PURE__ */ React.createElement("div", { className: "rec-who" }, /* @__PURE__ */ React.createElement("a", { className: "rec-name", href: rec.author.linkedin, target: "_blank", rel: "noopener noreferrer" }, rec.author.name, /* @__PURE__ */ React.createElement(Icon, { name: "ext", size: 10 })), /* @__PURE__ */ React.createElement("span", { className: "rec-headline" }, rec.author.headline)), /* @__PURE__ */ React.createElement("div", { className: "rec-meta" }, /* @__PURE__ */ React.createElement("span", { className: "rec-rel tone-" + (REL_TONE[rec.relationship] || "dim") }, REL_LABEL[rec.relationship] || rec.relationship), /* @__PURE__ */ React.createElement("span", { className: "rec-when" }, fmtRecDate(rec.date)))),
    /* @__PURE__ */ React.createElement("div", { className: "rec-org" }, /* @__PURE__ */ React.createElement(OrgMark, { org: rec.org, logo: rec.orgLogo }), /* @__PURE__ */ React.createElement("span", null, rec.org)),
    lead && /* @__PURE__ */ React.createElement("blockquote", { className: "rec-quote" }, lead.text),
    rec.claimIds && rec.claimIds.length > 0 && /* @__PURE__ */ React.createElement("div", { className: "rec-claims" }, /* @__PURE__ */ React.createElement("span", { className: "rec-claims-label" }, "Corroborates"), rec.claimIds.map((id) => /* @__PURE__ */ React.createElement("button", { key: id, type: "button", className: "rec-claim-chip", onClick: () => onOpenClaim(id) }, claims[id] && claims[id].label || id))),
    /* @__PURE__ */ React.createElement("div", { className: "rec-themes" }, (rec.themes || []).map((t) => /* @__PURE__ */ React.createElement("span", { key: t, className: "rec-theme" }, THEME_LABEL[t] || t))),
    /* @__PURE__ */ React.createElement("span", { className: "rec-open" }, "Read the full recommendation", /* @__PURE__ */ React.createElement(Icon, { name: "chevronRight", size: 12 }))
  );
};
const RecommendationModal = ({ rec, claims, onClose }) => {
  React.useEffect(() => {
    const onKey = (e) => {
      if (e.key === "Escape") {
        e.stopPropagation();
        onClose();
      }
    };
    window.addEventListener("keydown", onKey, true);
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", onKey, true);
      document.body.style.overflow = prev;
    };
  }, [onClose]);
  if (!rec) return null;
  return /* @__PURE__ */ React.createElement("div", { className: "recm-backdrop", onClick: onClose }, /* @__PURE__ */ React.createElement(
    "div",
    {
      className: "recm",
      role: "dialog",
      "aria-modal": "true",
      "aria-label": "Recommendation from " + rec.author.name,
      onClick: (e) => e.stopPropagation()
    },
    /* @__PURE__ */ React.createElement("header", { className: "recm-head" }, /* @__PURE__ */ React.createElement(Avatar, { person: rec.author, size: 64 }), /* @__PURE__ */ React.createElement("div", { className: "recm-who" }, /* @__PURE__ */ React.createElement("a", { className: "recm-name", href: rec.author.linkedin, target: "_blank", rel: "noopener noreferrer" }, rec.author.name, /* @__PURE__ */ React.createElement(Icon, { name: "ext", size: 12 })), /* @__PURE__ */ React.createElement("span", { className: "recm-headline" }, rec.author.headline), /* @__PURE__ */ React.createElement("div", { className: "recm-badges" }, /* @__PURE__ */ React.createElement("span", { className: "rec-rel tone-" + (REL_TONE[rec.relationship] || "dim") }, REL_LABEL[rec.relationship] || rec.relationship), /* @__PURE__ */ React.createElement("span", { className: "rec-when" }, fmtRecDate(rec.date)))), /* @__PURE__ */ React.createElement("button", { type: "button", className: "recm-x", "aria-label": "Close", onClick: onClose }, "\xD7")),
    /* @__PURE__ */ React.createElement("div", { className: "recm-org" }, /* @__PURE__ */ React.createElement(OrgMark, { org: rec.org, logo: rec.orgLogo }), /* @__PURE__ */ React.createElement("div", { className: "recm-org-text" }, /* @__PURE__ */ React.createElement("span", { className: "recm-org-name" }, rec.org), /* @__PURE__ */ React.createElement("span", { className: "recm-org-sub" }, "where they worked together"))),
    /* @__PURE__ */ React.createElement("div", { className: "recm-body" }, /* @__PURE__ */ React.createElement("p", { className: "recm-text" }, rec.text)),
    /* @__PURE__ */ React.createElement("footer", { className: "recm-foot" }, rec.claimIds && rec.claimIds.length > 0 && /* @__PURE__ */ React.createElement("div", { className: "rec-claims" }, /* @__PURE__ */ React.createElement("span", { className: "rec-claims-label" }, "Corroborates"), rec.claimIds.map((id) => /* @__PURE__ */ React.createElement("span", { key: id, className: "rec-claim-chip" }, claims[id] && claims[id].label || id))), /* @__PURE__ */ React.createElement("div", { className: "rec-themes" }, (rec.themes || []).map((t) => /* @__PURE__ */ React.createElement("span", { key: t, className: "rec-theme" }, THEME_LABEL[t] || t))), /* @__PURE__ */ React.createElement("a", { className: "rec-source", href: rec.author.linkedin, target: "_blank", rel: "noopener noreferrer" }, "See it on LinkedIn ", /* @__PURE__ */ React.createElement(Icon, { name: "ext", size: 10 })))
  ));
};
const RecommendationsPage = () => {
  const D = window.SITE_DATA;
  const all = D.recommendations || [];
  const claims = D.recommendationClaims || {};
  const [q, setQ] = React.useState("");
  const [theme, setTheme] = React.useState(null);
  const [rel, setRel] = React.useState(null);
  const [claim, setClaim] = React.useState(null);
  const dl = React.useRef();
  if (dl.current === void 0) {
    dl.current = window.DEEP_LINK || null;
    window.DEEP_LINK = null;
  }
  const [openId, setOpenId] = React.useState(() => dl.current && dl.current.recId || null);
  const openRec = openId ? all.find((r) => r.id === openId) : null;
  const themeCounts = {}, relCounts = {};
  all.forEach((r) => {
    (r.themes || []).forEach((t) => themeCounts[t] = (themeCounts[t] || 0) + 1);
    relCounts[r.relationship] = (relCounts[r.relationship] || 0) + 1;
  });
  const needle = q.trim().toLowerCase();
  const shown = all.filter(
    (r) => (!theme || (r.themes || []).includes(theme)) && (!rel || r.relationship === rel) && (!claim || (r.claimIds || []).includes(claim)) && (!needle || (r.text + " " + r.author.name + " " + r.author.headline + " " + r.org).toLowerCase().includes(needle))
  );
  const corroborated = Object.keys(claims).filter((id) => all.some((r) => (r.claimIds || []).includes(id)));
  const clearAll = () => {
    setTheme(null);
    setRel(null);
    setClaim(null);
    setQ("");
  };
  const filtered = theme || rel || claim || needle;
  return /* @__PURE__ */ React.createElement("div", { className: "page", style: { maxWidth: 1180 } }, /* @__PURE__ */ React.createElement("div", { className: "page-head" }, /* @__PURE__ */ React.createElement("span", { className: "eyebrow" }, "Corroboration"), /* @__PURE__ */ React.createElement("h1", { className: "page-title" }, "Recommendations"), /* @__PURE__ */ React.createElement("p", { className: "page-sub" }, all.length, " recommendations written on LinkedIn, unedited. The reason they are here rather than on a testimonials slide: ", corroborated.length, " specific claims on this r\xE9sum\xE9 are independently described by people who watched the work happen \u2014 in several cases by more than one person, years apart, without being prompted.")), /* @__PURE__ */ React.createElement("section", { className: "rec-corrob" }, /* @__PURE__ */ React.createElement("div", { className: "rec-corrob-head" }, /* @__PURE__ */ React.createElement("span", { className: "impact-label" }, "Claims with independent witnesses"), claim && /* @__PURE__ */ React.createElement("button", { className: "btn btn-sm btn-ghost", onClick: () => setClaim(null) }, /* @__PURE__ */ React.createElement(Icon, { name: "x", size: 12 }), " Show all")), /* @__PURE__ */ React.createElement("div", { className: "rec-corrob-grid" }, corroborated.map((id) => ({ id, n: all.filter((r) => (r.claimIds || []).includes(id)).length })).sort((a, b) => b.n - a.n).map(({ id, n }) => /* @__PURE__ */ React.createElement(
    "button",
    {
      key: id,
      type: "button",
      className: "rec-corrob-cell" + (claim === id ? " is-active" : ""),
      onClick: () => setClaim(claim === id ? null : id)
    },
    /* @__PURE__ */ React.createElement("span", { className: "rec-corrob-n" }, n),
    /* @__PURE__ */ React.createElement("span", { className: "rec-corrob-label" }, claims[id].label),
    /* @__PURE__ */ React.createElement("span", { className: "rec-corrob-sub" }, n === 1 ? "witness" : "independent witnesses")
  )))), /* @__PURE__ */ React.createElement("div", { className: "catalog-toolbar" }, /* @__PURE__ */ React.createElement("div", { className: "searchbox" }, /* @__PURE__ */ React.createElement(Icon, { name: "search", size: 14 }), /* @__PURE__ */ React.createElement("input", { placeholder: "Search recommendations\u2026", value: q, onChange: (e) => setQ(e.target.value) })), /* @__PURE__ */ React.createElement("span", { style: { flex: 1 } }), filtered && /* @__PURE__ */ React.createElement("button", { className: "btn btn-sm btn-ghost", onClick: clearAll }, /* @__PURE__ */ React.createElement(Icon, { name: "x", size: 12 }), " Clear"), /* @__PURE__ */ React.createElement("span", { style: { fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--text-mute)" } }, shown.length, " / ", all.length)), /* @__PURE__ */ React.createElement("div", { className: "rec-facets" }, /* @__PURE__ */ React.createElement("div", { className: "rec-facet" }, /* @__PURE__ */ React.createElement("span", { className: "rec-facet-label" }, "Evidence of"), Object.entries(themeCounts).sort((a, b) => b[1] - a[1]).map(([t, n]) => /* @__PURE__ */ React.createElement(
    "button",
    {
      key: t,
      type: "button",
      className: "rec-pill" + (theme === t ? " is-active" : ""),
      onClick: () => setTheme(theme === t ? null : t)
    },
    THEME_LABEL[t] || t,
    /* @__PURE__ */ React.createElement("span", { className: "rec-pill-n" }, n)
  ))), /* @__PURE__ */ React.createElement("div", { className: "rec-facet" }, /* @__PURE__ */ React.createElement("span", { className: "rec-facet-label" }, "Written from"), Object.entries(relCounts).sort((a, b) => b[1] - a[1]).map(([r, n]) => /* @__PURE__ */ React.createElement(
    "button",
    {
      key: r,
      type: "button",
      className: "rec-pill" + (rel === r ? " is-active" : ""),
      onClick: () => setRel(rel === r ? null : r)
    },
    REL_LABEL[r] || r,
    /* @__PURE__ */ React.createElement("span", { className: "rec-pill-n" }, n)
  )))), /* @__PURE__ */ React.createElement("div", { className: "rec-grid" }, shown.map((r) => /* @__PURE__ */ React.createElement(RecommendationCard, { key: r.id, rec: r, claims, onOpenClaim: setClaim, onOpen: setOpenId }))), openRec && /* @__PURE__ */ React.createElement(RecommendationModal, { rec: openRec, claims, onClose: () => setOpenId(null) }), shown.length === 0 && /* @__PURE__ */ React.createElement("div", { className: "cmdk-empty", style: { border: "1px solid var(--line)", borderRadius: "var(--rad)" } }, "Nothing matches that combination."));
};
const RoleRecommendations = ({ roleId }) => {
  const D = window.SITE_DATA;
  const recs = (D.recommendations || []).filter((r) => (r.roleIds || []).includes(roleId));
  const [openId, setOpenId] = React.useState(null);
  if (!recs.length) return null;
  const openRec = openId ? recs.find((r) => r.id === openId) : null;
  return /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("div", { className: "rec-grid rec-grid-inline" }, recs.map((r) => /* @__PURE__ */ React.createElement(
    RecommendationCard,
    {
      key: r.id,
      rec: r,
      claims: D.recommendationClaims || {},
      onOpenClaim: () => {
        var _a;
        return (_a = window.GO) == null ? void 0 : _a.call(window, "recommendations");
      },
      onOpen: setOpenId
    }
  ))), openRec && /* @__PURE__ */ React.createElement(
    RecommendationModal,
    {
      rec: openRec,
      claims: D.recommendationClaims || {},
      onClose: () => setOpenId(null)
    }
  ));
};
window.Avatar = Avatar;
window.RecommendationCard = RecommendationCard;
window.RecommendationModal = RecommendationModal;
window.RecommendationsPage = RecommendationsPage;
window.RoleRecommendations = RoleRecommendations;
const THEME_CUES = {
  leadership: ["lead", "leader", "leadership", "manage", "manager", "management", "team", "director", "org", "hire", "hiring", "work for", "like to work", "boss", "style", "culture", "run a"],
  mentoring: ["mentor", "coach", "grow", "growth", "develop", "junior", "teach", "career", "onboard", "learn from", "report to"],
  platform: ["kubernetes", "k8s", "eks", "platform", "container", "helm", "cluster", "scale", "scaling"],
  "cloud-architecture": ["aws", "azure", "cloud", "architect", "architecture", "migrat", "infrastructure", "network", "technical", "hands-on", "depth", "expertise"],
  finops: ["cost", "spend", "finops", "budget", "saving", "optimi", "efficien", "waste", "non-prod", "nonprod", "off-hours"],
  iac: ["terraform", "pulumi", "iac", "policy-as-code", "opa", "declarative"],
  ai: ["ai", "agentic", "llm", "genai", "ml", "automation", "automate"],
  communication: ["communicat", "explain", "present", "executive", "articulate", "clarity", "document"],
  stakeholder: ["stakeholder", "vendor", "partner", "influence", "politic", "consensus", "cross-functional", "negotiat"],
  collaboration: ["collaborat", "cross-team", "together", "peer"],
  delivery: ["deliver", "ship", "deadline", "execut", "result", "reliab", "dependable", "on time"],
  innovation: ["innovat", "modern", "transform", "forward", "creative", "new idea"],
  "problem-solving": ["problem", "solve", "complex", "debug", "troubleshoot", "incident", "root cause"]
};
const CLAIM_CUES = {
  "env-claims": ["environment claim", "env claim", "environment-claim", "lower environment", "non-prod", "nonprod", "scale down", "off-hours", "f1n"],
  "vpc-endpoints": ["vpc endpoint", "interface endpoint", "endpoint hub", "vpc"],
  "eks-hardened": ["eks", "kubernetes", "k8s", "hardened", "cis"],
  "finops-30": ["finops", "cost optimi", "cloud cost", "spend reduction", "30%"],
  "team-growth": ["grew the team", "team growth", "build a team", "1 to 18", "hiring"],
  "ai-pivot": ["ai", "agentic", "genai", "llm"],
  "boa-mainframe": ["mainframe", "bank of america", "ispf", "cobol"],
  "iac": ["terraform", "pulumi", "policy-as-code"]
};
const cueRE = (cue) => {
  const esc = cue.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp("\\b" + esc + (cue.length <= 3 ? "\\b" : ""), "i");
};
const COMPILED_CUES = Object.entries(THEME_CUES).map(([theme, cues]) => [theme, cues.map(cueRE)]);
const COMPILED_CLAIM_CUES = Object.entries(CLAIM_CUES).map(([id, cues]) => [id, cues.map(cueRE)]);
const claimsInQuestion = (question) => {
  const q = String(question || "");
  const hits = [];
  COMPILED_CLAIM_CUES.forEach(([id, res]) => {
    if (res.some((re) => re.test(q))) hits.push(id);
  });
  return hits;
};
const themesInQuestion = (question) => {
  const q = String(question || "");
  const hits = [];
  COMPILED_CUES.forEach(([theme, res]) => {
    if (res.some((re) => re.test(q))) hits.push(theme);
  });
  return hits;
};
const VANTAGE_PREF = {
  people: {
    "reported-to-geoff": 1,
    "managed-geoff": 0.95,
    "geoff-senior": 0.6,
    "senior-to-geoff": 0.6,
    "same-team": 0.5,
    "different-teams": 0.35,
    "different-company": 0.3
  },
  technical: {
    "geoff-senior": 0.9,
    "senior-to-geoff": 0.95,
    "same-team": 0.85,
    "reported-to-geoff": 0.8,
    "different-teams": 0.7,
    "managed-geoff": 0.6,
    "different-company": 0.8
  },
  outward: {
    "different-company": 1,
    "different-teams": 0.9,
    "senior-to-geoff": 0.7,
    "same-team": 0.5,
    "managed-geoff": 0.6,
    "reported-to-geoff": 0.4,
    "geoff-senior": 0.4
  }
};
const questionClass = (themes) => {
  const people = themes.filter((t) => t === "leadership" || t === "mentoring").length;
  const outward = themes.filter((t) => t === "stakeholder" || t === "collaboration" || t === "communication").length;
  const tech = themes.length - people - outward;
  if (people > tech && people >= outward) return "people";
  if (outward > tech && outward >= people) return "outward";
  return "technical";
};
const recencyScore = (iso, now) => {
  const then = (/* @__PURE__ */ new Date(iso + "T00:00:00")).getTime();
  if (!isFinite(then)) return 0;
  const years = (now - then) / (365.25 * 24 * 3600 * 1e3);
  return Math.exp(-Math.max(0, years) / 4);
};
const REL_PHRASE = {
  "managed-geoff": "his manager",
  "reported-to-geoff": "a direct report",
  "senior-to-geoff": "an executive above him",
  "geoff-senior": "a senior engineer on his org",
  "same-team": "a teammate",
  "different-teams": "a partner team",
  "different-company": "from the vendor side"
};
const recommendationsFor = (question, opts) => {
  const o = opts || {};
  const limit = o.limit || 2;
  const exclude = new Set(o.exclude || []);
  const all = window.SITE_DATA && window.SITE_DATA.recommendations || [];
  if (!all.length) return [];
  const qThemes = themesInQuestion(question);
  const qClaims = claimsInQuestion(question);
  if (!qThemes.length && !qClaims.length) return [];
  const klass = questionClass(qThemes);
  const pref = VANTAGE_PREF[klass] || VANTAGE_PREF.technical;
  const now = Date.now();
  const scored = all.filter((r) => !exclude.has(r.id)).map((r) => {
    const matched = (r.themes || []).filter((t) => qThemes.includes(t));
    const claimHit = (r.claimIds || []).filter((c) => qClaims.includes(c));
    if (!matched.length && !claimHit.length) return null;
    const themeMatch = qThemes.length ? matched.length / qThemes.length : 0;
    const claimMatch = qClaims.length ? claimHit.length / qClaims.length : 0;
    const score = 0.35 * Math.min(1, themeMatch) + 0.2 * Math.min(1, claimMatch) + 0.22 * (r.strength || 0) + 0.15 * recencyScore(r.date, now) + 0.08 * (pref[r.relationship] || 0.4);
    let quote = null, best = -1;
    (r.pullQuotes || []).forEach((pq) => {
      const n = (pq.themes || []).filter((t) => qThemes.includes(t)).length;
      if (n > best) {
        best = n;
        quote = pq;
      }
    });
    const claims = window.SITE_DATA && window.SITE_DATA.recommendationClaims || {};
    const subject = claimHit.length ? claims[claimHit[0]] && claims[claimHit[0]].label || claimHit[0] : THEME_LABEL[matched[0]] || matched[0];
    return {
      rec: r,
      score,
      quote: quote || (r.pullQuotes || [])[0] || null,
      why: (REL_PHRASE[r.relationship] || "a colleague") + ", on " + String(subject).toLowerCase()
    };
  }).filter(Boolean).sort((a, b) => b.score - a.score);
  return scored.slice(0, limit);
};
const RecommendationQuote = ({ hit }) => {
  if (!hit || !hit.quote) return null;
  const r = hit.rec;
  return /* @__PURE__ */ React.createElement("figure", { className: "recq" }, /* @__PURE__ */ React.createElement("div", { className: "recq-head" }, /* @__PURE__ */ React.createElement(Avatar, { person: r.author, size: 30 }), /* @__PURE__ */ React.createElement("div", { className: "recq-who" }, /* @__PURE__ */ React.createElement("span", { className: "recq-name" }, r.author.name), /* @__PURE__ */ React.createElement("span", { className: "recq-why" }, hit.why, " \xB7 ", r.org)), /* @__PURE__ */ React.createElement("span", { className: "recq-when" }, fmtRecDate(r.date))), /* @__PURE__ */ React.createElement("blockquote", { className: "recq-quote" }, hit.quote.text), /* @__PURE__ */ React.createElement("div", { className: "recq-foot" }, /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      className: "recq-link",
      onClick: () => {
        var _a;
        return (_a = window.GO) == null ? void 0 : _a.call(window, "recommendations", { recId: r.id });
      }
    },
    "Read the full recommendation",
    /* @__PURE__ */ React.createElement(Icon, { name: "chevronRight", size: 11 })
  ), /* @__PURE__ */ React.createElement("a", { className: "recq-link", href: r.author.linkedin, target: "_blank", rel: "noopener noreferrer" }, "On LinkedIn", /* @__PURE__ */ React.createElement(Icon, { name: "ext", size: 10 }))));
};
window.recommendationsFor = recommendationsFor;
window.RecommendationQuote = RecommendationQuote;
window.themesInQuestion = themesInQuestion;
window.claimsInQuestion = claimsInQuestion;
