// Code generated by tools/jsxbuild from Shell.jsx. DO NOT EDIT.
var __defProp = Object.defineProperty;
var __defProps = Object.defineProperties;
var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
const { useState, useEffect, useRef, useMemo, useCallback } = React;
const ALL_NAV = [
  { section: "Candidate" },
  { id: "chat", label: "JD Chat", icon: "sparkles" },
  { id: "resume", label: "Resume", icon: "file" },
  { section: "Catalogs" },
  { id: "projects", label: "Projects", icon: "folder" },
  { id: "achievements", label: "Achievements", icon: "award", feature: "achievements" },
  { id: "recommendations", label: "Recommendations", icon: "award" },
  { id: "articles", label: "Articles", icon: "book" },
  { id: "resources", label: "Resources", icon: "layers", feature: "resources" },
  { section: "Personal" },
  { id: "about", label: "About Geoff", icon: "user" },
  { id: "contact", label: "Contact", icon: "mail" }
];
const featureOn = (name) => {
  if (!name) return true;
  const f = window.SITE_FEATURES || {};
  return f[name] !== false;
};
const NAV = (() => {
  const kept = ALL_NAV.filter((item) => item.section || featureOn(item.feature));
  const out = [];
  for (let i = 0; i < kept.length; i++) {
    const item = kept[i];
    if (!item.section) {
      out.push(item);
      continue;
    }
    let hasChild = false;
    for (let j = i + 1; j < kept.length && !kept[j].section; j++) hasChild = true;
    if (hasChild) out.push(item);
  }
  let n = 0;
  return out.map((item) => item.section ? item : __spreadProps(__spreadValues({}, item), { meta: "\u2318" + ++n }));
})();
const Sidebar = ({ route, setRoute: setRoute2, onOpenPalette, sidebarOpen, setSidebarOpen }) => {
  const p = window.SITE_DATA.profile;
  return /* @__PURE__ */ React.createElement("aside", { className: "sidebar" + (sidebarOpen ? " open" : "") }, /* @__PURE__ */ React.createElement("div", { className: "brand", style: { cursor: "pointer" }, onClick: () => {
    setRoute2("chat");
    setSidebarOpen(false);
  } }, /* @__PURE__ */ React.createElement("div", { className: "brand-mark" }, /* @__PURE__ */ React.createElement("img", { src: "assets/geoff.png", alt: "Geoff" })), /* @__PURE__ */ React.createElement("div", { style: { lineHeight: 1.1 } }, /* @__PURE__ */ React.createElement("div", { style: { color: "var(--text)", fontWeight: 600 } }, "geoff", /* @__PURE__ */ React.createElement("span", { style: { color: "var(--text-mute)" } }, "miller"), ".cloud"), /* @__PURE__ */ React.createElement("div", { style: { color: "var(--text-mute)", fontSize: 10.5, marginTop: 2 } }, "v", (/* @__PURE__ */ new Date()).getFullYear().toString().slice(2), ".4"))), /* @__PURE__ */ React.createElement("button", { className: "btn", style: { justifyContent: "space-between", width: "100%" }, onClick: onOpenPalette }, /* @__PURE__ */ React.createElement("span", { className: "hstack", style: { gap: 8, color: "var(--text-mute)" } }, /* @__PURE__ */ React.createElement(Icon, { name: "search", size: 14 }), /* @__PURE__ */ React.createElement("span", null, "Search\u2026")), /* @__PURE__ */ React.createElement("span", { className: "kbd" }, "\u2318K")), /* @__PURE__ */ React.createElement("nav", { className: "nav" }, NAV.map((item, i) => item.section ? /* @__PURE__ */ React.createElement("div", { key: "s" + i, className: "nav-section" }, item.section) : /* @__PURE__ */ React.createElement(
    "a",
    {
      key: item.id,
      className: "nav-link" + (route === item.id ? " active" : ""),
      onClick: () => {
        setRoute2(item.id);
        setSidebarOpen(false);
      }
    },
    /* @__PURE__ */ React.createElement(Icon, { name: item.icon, size: 15, className: "icon" }),
    /* @__PURE__ */ React.createElement("span", null, item.label),
    /* @__PURE__ */ React.createElement("span", { className: "nav-meta" }, item.meta)
  ))), /* @__PURE__ */ React.createElement("div", { className: "sidebar-foot" }, /* @__PURE__ */ React.createElement("div", { className: "hstack", style: { justifyContent: "space-between" } }, /* @__PURE__ */ React.createElement("span", { className: "hstack", style: { gap: 6 } }, /* @__PURE__ */ React.createElement("span", { className: "status-dot" }), /* @__PURE__ */ React.createElement("span", null, "Available \u2014 selectively"))), /* @__PURE__ */ React.createElement("div", { className: "hstack", style: { gap: 8, color: "var(--text-faint)", fontSize: 10 } }, /* @__PURE__ */ React.createElement(Icon, { name: "github", size: 12 }), /* @__PURE__ */ React.createElement("span", null, p.links.github.replace("github.com/", ""))), /* @__PURE__ */ React.createElement("div", { className: "hstack", style: { gap: 8, color: "var(--text-faint)", fontSize: 10 } }, /* @__PURE__ */ React.createElement(Icon, { name: "linkedin", size: 12 }), /* @__PURE__ */ React.createElement("span", null, p.links.linkedin.replace("linkedin.com/in/", "")))));
};
const HeaderBar = ({ onToggleTheme, theme, onOpenPalette, onToggleMobile }) => /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("div", { className: "mobile-top" }, /* @__PURE__ */ React.createElement("button", { className: "btn btn-icon btn-ghost", onClick: onToggleMobile, "aria-label": "Menu" }, /* @__PURE__ */ React.createElement(Icon, { name: "menu", size: 18 })), /* @__PURE__ */ React.createElement("div", { className: "brand", style: { flex: 1, cursor: "pointer" }, onClick: () => setRoute("chat") }, /* @__PURE__ */ React.createElement("div", { className: "brand-mark" }, /* @__PURE__ */ React.createElement("img", { src: "assets/geoff.png", alt: "Geoff" })), /* @__PURE__ */ React.createElement("span", { style: { fontSize: 13 } }, "geoffmiller.cloud")), /* @__PURE__ */ React.createElement("button", { className: "btn btn-icon btn-ghost", onClick: onOpenPalette, "aria-label": "Search" }, /* @__PURE__ */ React.createElement(Icon, { name: "search", size: 16 })), /* @__PURE__ */ React.createElement("button", { className: "btn btn-icon btn-ghost", onClick: onToggleTheme, "aria-label": "Theme" }, /* @__PURE__ */ React.createElement(Icon, { name: theme === "light" ? "moon" : "sun", size: 16 }))));
window.Sidebar = Sidebar;
window.HeaderBar = HeaderBar;
window.NAV = NAV;
window.ALL_NAV = ALL_NAV;
window.featureOn = featureOn;
