// Code generated by tools/jsxbuild from Viz.jsx. DO NOT EDIT.
const DiagramExplorer = ({ viewBox, ariaLabel, notes, children }) => {
  const [open, setOpen] = React.useState(null);
  const wrapRef = React.useRef(null);
  React.useEffect(() => {
    if (!open) return void 0;
    const onKey = (e) => {
      if (e.key === "Escape") {
        e.stopPropagation();
        setOpen(null);
      }
    };
    window.addEventListener("keydown", onKey, true);
    return () => window.removeEventListener("keydown", onKey, true);
  }, [open]);
  const note = open ? notes[open] : null;
  return /* @__PURE__ */ React.createElement("div", { className: "dgx", ref: wrapRef, onClick: () => setOpen(null) }, /* @__PURE__ */ React.createElement("svg", { viewBox, xmlns: "http://www.w3.org/2000/svg", role: "img", "aria-label": ariaLabel }, children({ open, setOpen, notes })), note && /* @__PURE__ */ React.createElement(
    "div",
    {
      className: "dgx-card",
      role: "dialog",
      "aria-label": note.title,
      onClick: (e) => e.stopPropagation()
    },
    /* @__PURE__ */ React.createElement("div", { className: "dgx-card-head" }, /* @__PURE__ */ React.createElement("span", { className: "dgx-card-title" }, note.title), /* @__PURE__ */ React.createElement("button", { type: "button", className: "dgx-card-x", "aria-label": "Close", onClick: () => setOpen(null) }, "\xD7")),
    /* @__PURE__ */ React.createElement("p", { className: "dgx-card-body" }, note.body),
    note.detail && /* @__PURE__ */ React.createElement("p", { className: "dgx-card-detail" }, note.detail)
  ));
};
const DgxBox = ({ id, x, y, w, h, color, title, sub, open, setOpen, dashed }) => {
  const on = open === id;
  return /* @__PURE__ */ React.createElement(
    "g",
    {
      className: "dgx-node" + (on ? " is-open" : ""),
      role: "button",
      tabIndex: 0,
      "aria-label": title + (sub ? ". " + sub : "") + ". Open detail.",
      onClick: (e) => {
        e.stopPropagation();
        setOpen(on ? null : id);
      },
      onKeyDown: (e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          setOpen(on ? null : id);
        }
      }
    },
    /* @__PURE__ */ React.createElement(
      "rect",
      {
        x,
        y,
        width: w,
        height: h,
        rx: "6",
        fill: "var(--bg-1)",
        stroke: color,
        strokeWidth: on ? 2.2 : 1.4,
        strokeDasharray: dashed ? "4 4" : void 0
      }
    ),
    /* @__PURE__ */ React.createElement(
      "text",
      {
        x: x + w / 2,
        y: y + (sub ? 22 : h / 2 + 4),
        textAnchor: "middle",
        fontFamily: "JetBrains Mono",
        fontSize: "10.5",
        fill: color
      },
      title
    ),
    sub && /* @__PURE__ */ React.createElement(
      "text",
      {
        x: x + w / 2,
        y: y + 38,
        textAnchor: "middle",
        fontFamily: "JetBrains Mono",
        fontSize: "9",
        fill: "var(--text-mute)"
      },
      sub
    ),
    /* @__PURE__ */ React.createElement("circle", { cx: x + w - 11, cy: y + 11, r: "6.5", fill: "none", stroke: color, strokeOpacity: ".5", strokeWidth: "1" }),
    /* @__PURE__ */ React.createElement(
      "text",
      {
        x: x + w - 11,
        y: y + 14.5,
        textAnchor: "middle",
        fontFamily: "JetBrains Mono",
        fontSize: "8.5",
        fill: color,
        opacity: ".75"
      },
      "i"
    )
  );
};
const VizFrame = ({ title, note, source, children }) => /* @__PURE__ */ React.createElement("figure", { className: "vizchart" }, (title || note) && /* @__PURE__ */ React.createElement("figcaption", { className: "vizchart-head" }, title && /* @__PURE__ */ React.createElement("span", { className: "vizchart-title" }, title), note && /* @__PURE__ */ React.createElement("span", { className: "vizchart-note" }, note)), children, source && /* @__PURE__ */ React.createElement("p", { className: "vizchart-src" }, source));
const AreaChart = ({ data }) => {
  if (!data || !Array.isArray(data.series) || !Array.isArray(data.xLabels)) return null;
  const n = data.xLabels.length;
  if (n < 2) return null;
  const w = 640, h = 200, padL = 36, padR = 14, padT = 20, padB = 28;
  const iw = w - padL - padR, ih = h - padT - padB;
  const all = data.series.flatMap((s) => s.values || []);
  if (!all.length) return null;
  const maxV = data.yMax || Math.max(...all, 100);
  const ticks = data.yTicks || [0, 0.25, 0.5, 0.75, 1].map((f) => Math.round(maxV * f));
  const x = (i) => padL + iw * i / (n - 1);
  const y = (v) => padT + ih - ih * v / maxV;
  const linePath = (vals) => vals.map((v, i) => (i ? "L" : "M") + x(i) + " " + y(v)).join(" ");
  const areaPath = (vals) => linePath(vals) + ` L${x(n - 1)} ${padT + ih} L${padL} ${padT + ih} Z`;
  return /* @__PURE__ */ React.createElement(VizFrame, { title: data.title, note: data.note, source: data.source }, /* @__PURE__ */ React.createElement(
    "svg",
    {
      className: "chart-svg",
      viewBox: `0 0 ${w} ${h}`,
      role: "img",
      "aria-label": data.alt || data.title || "Area chart"
    },
    /* @__PURE__ */ React.createElement("defs", null, data.series.map((s, i) => /* @__PURE__ */ React.createElement("linearGradient", { key: i, id: "g" + i, x1: "0", x2: "0", y1: "0", y2: "1" }, /* @__PURE__ */ React.createElement("stop", { offset: "0%", stopColor: s.color, stopOpacity: "0.35" }), /* @__PURE__ */ React.createElement("stop", { offset: "100%", stopColor: s.color, stopOpacity: "0" })))),
    ticks.map((t, i) => /* @__PURE__ */ React.createElement("g", { key: i }, /* @__PURE__ */ React.createElement("line", { x1: padL, x2: w - padR, y1: y(t), y2: y(t), stroke: "var(--line-soft)", strokeDasharray: "2 3" }), /* @__PURE__ */ React.createElement("text", { x: padL - 6, y: y(t) + 3, textAnchor: "end", fontFamily: "JetBrains Mono", fontSize: "9", fill: "var(--text-faint)" }, t))),
    data.series.map((s, i) => /* @__PURE__ */ React.createElement("g", { key: i }, /* @__PURE__ */ React.createElement("path", { d: areaPath(s.values), fill: "url(#g" + i + ")" }), /* @__PURE__ */ React.createElement(
      "path",
      {
        d: linePath(s.values),
        fill: "none",
        stroke: s.color,
        strokeWidth: "1.75",
        strokeLinejoin: "round",
        style: { filter: `drop-shadow(0 0 6px ${s.color})` }
      }
    ), s.values.map((v, j) => /* @__PURE__ */ React.createElement("circle", { key: j, cx: x(j), cy: y(v), r: "2.4", fill: s.color })))),
    data.xLabels.map((lbl, i) => /* @__PURE__ */ React.createElement("text", { key: i, x: x(i), y: h - 8, textAnchor: "middle", fontFamily: "JetBrains Mono", fontSize: "9", fill: "var(--text-mute)" }, lbl))
  ), /* @__PURE__ */ React.createElement("div", { className: "chart-legend" }, data.series.map((s, i) => /* @__PURE__ */ React.createElement("span", { key: i }, /* @__PURE__ */ React.createElement("span", { className: "swatch", style: { background: s.color, boxShadow: `0 0 8px ${s.color}` } }), " ", s.label))));
};
const BenchmarkChart = ({ data }) => {
  if (!data || !Array.isArray(data.rows) || !data.rows.length) return null;
  const unit = data.unit || "";
  const bound = data.max || Math.max(...data.rows.map((r) => (r.hi != null ? r.hi : r.value) || 0), 1);
  const pct = (v) => Math.max(0, Math.min(100, v / bound * 100));
  const fmt = (v) => `${v}${unit}`;
  return /* @__PURE__ */ React.createElement(VizFrame, { title: data.title, note: data.note, source: data.source }, /* @__PURE__ */ React.createElement("div", { className: "bench" }, data.rows.map((r, i) => {
    const isRange = r.lo != null && r.hi != null;
    const lo = isRange ? r.lo : 0;
    const hi = isRange ? r.hi : r.value || 0;
    const label = isRange ? `${r.lo}\u2013${r.hi}${unit}` : fmt(r.value || 0);
    return /* @__PURE__ */ React.createElement("div", { key: i, className: "bench-row" + (r.mine ? " is-mine" : "") }, /* @__PURE__ */ React.createElement("div", { className: "bench-label" }, /* @__PURE__ */ React.createElement("span", { className: "bench-name" }, r.label), r.sub && /* @__PURE__ */ React.createElement("span", { className: "bench-sub" }, r.sub)), /* @__PURE__ */ React.createElement("div", { className: "bench-track", role: "img", "aria-label": `${r.label}: ${label}` }, /* @__PURE__ */ React.createElement(
      "span",
      {
        className: "bench-fill",
        style: { left: pct(lo) + "%", width: Math.max(pct(hi) - pct(lo), 1.2) + "%" }
      }
    ), isRange && /* @__PURE__ */ React.createElement("span", { className: "bench-cap", style: { left: pct(lo) + "%" } }), /* @__PURE__ */ React.createElement("span", { className: "bench-cap", style: { left: pct(hi) + "%" } })), /* @__PURE__ */ React.createElement("div", { className: "bench-val" }, label), r.source && /* @__PURE__ */ React.createElement("div", { className: "bench-src" }, r.mine ? "Geoff's own figure \u2014 " : "", r.source));
  })));
};
const ShareBars = ({ data }) => {
  if (!data || !Array.isArray(data.rows) || !data.rows.length) return null;
  const legend = data.rows[0].segments || [];
  if (!legend.length) return null;
  return /* @__PURE__ */ React.createElement(VizFrame, { title: data.title, note: data.note, source: data.source }, /* @__PURE__ */ React.createElement("div", { className: "share" }, data.rows.map((r, i) => {
    const segs = r.segments || [];
    const total = segs.reduce((a, s) => a + (s.value || 0), 0) || 1;
    return /* @__PURE__ */ React.createElement("div", { key: i, className: "share-row" }, /* @__PURE__ */ React.createElement("div", { className: "share-label" }, /* @__PURE__ */ React.createElement("span", { className: "share-name" }, r.label), r.sub && /* @__PURE__ */ React.createElement("span", { className: "share-sub" }, r.sub)), /* @__PURE__ */ React.createElement(
      "div",
      {
        className: "share-bar",
        role: "img",
        "aria-label": r.label + ": " + segs.map((s) => `${s.label} ${Math.round(s.value / total * 100)}%`).join(", ")
      },
      segs.map((s, j) => {
        const share = (s.value || 0) / total * 100;
        return /* @__PURE__ */ React.createElement(
          "span",
          {
            key: j,
            className: "share-seg",
            style: { width: share + "%", background: s.color, color: s.color }
          },
          /* @__PURE__ */ React.createElement("span", { className: "share-seg-val" }, Math.round(share), "%")
        );
      })
    ), r.source && /* @__PURE__ */ React.createElement("div", { className: "share-src" }, r.mine ? "Geoff's own figure \u2014 " : "", r.source));
  })), /* @__PURE__ */ React.createElement("div", { className: "chart-legend" }, legend.map((s, i) => /* @__PURE__ */ React.createElement("span", { key: i }, /* @__PURE__ */ React.createElement("span", { className: "swatch", style: { background: s.color, boxShadow: `0 0 8px ${s.color}` } }), " ", s.label))));
};
const GateFlow = ({ data }) => {
  const stages = data && data.stages || [];
  const gates = data && data.gates || [];
  if (stages.length < 2 || !gates.length) return null;
  const [open, setOpen] = React.useState(gates[0].id);
  const sel = gates.find((g) => g.id === open) || null;
  return /* @__PURE__ */ React.createElement(VizFrame, { title: data.title, note: data.note, source: data.source }, /* @__PURE__ */ React.createElement("div", { className: "gateflow" }, /* @__PURE__ */ React.createElement("div", { className: "gf-track" }, stages.map((s, i) => /* @__PURE__ */ React.createElement(React.Fragment, { key: s.id || i }, /* @__PURE__ */ React.createElement("div", { className: "gf-stage" }, /* @__PURE__ */ React.createElement("span", { className: "gf-stage-label" }, s.label), s.sub && /* @__PURE__ */ React.createElement("span", { className: "gf-stage-sub" }, s.sub)), gates[i] && /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      className: "gf-gate" + (open === gates[i].id ? " is-open" : ""),
      "aria-expanded": open === gates[i].id,
      onClick: () => setOpen(open === gates[i].id ? null : gates[i].id)
    },
    /* @__PURE__ */ React.createElement("span", { className: "gf-gate-dot" }, i + 1),
    /* @__PURE__ */ React.createElement("span", { className: "gf-gate-label" }, gates[i].label)
  )))), sel && /* @__PURE__ */ React.createElement("div", { className: "gf-detail" }, /* @__PURE__ */ React.createElement("div", { className: "gf-detail-head" }, /* @__PURE__ */ React.createElement("span", { className: "gf-detail-title" }, sel.title || sel.label), sel.border && /* @__PURE__ */ React.createElement("span", { className: "gf-detail-border" }, sel.border)), sel.detail && /* @__PURE__ */ React.createElement("p", { className: "gf-detail-body" }, sel.detail), Array.isArray(sel.checks) && sel.checks.length > 0 && /* @__PURE__ */ React.createElement("ul", { className: "gf-checks" }, sel.checks.map((c, i) => /* @__PURE__ */ React.createElement("li", { key: i }, /* @__PURE__ */ React.createElement("span", { className: "gf-check-what" }, c.what), c.why && /* @__PURE__ */ React.createElement("span", { className: "gf-check-why" }, c.why)))))));
};
const CARD_TONES = { cyan: "var(--neon-cyan)", pink: "var(--neon-pink)", amber: "var(--neon-amber)", purple: "var(--neon-purple)" };
const CardGrid = ({ data }) => {
  const cards = data && data.cards || [];
  if (!cards.length) return null;
  const min = data.min || 210;
  return /* @__PURE__ */ React.createElement(VizFrame, { title: data.title, note: data.note, source: data.source }, /* @__PURE__ */ React.createElement("div", { className: "cardgrid", style: { gridTemplateColumns: `repeat(auto-fit, minmax(${min}px, 1fr))` } }, cards.map((c, i) => /* @__PURE__ */ React.createElement("div", { key: c.id || i, className: "cg-card", style: { borderTopColor: CARD_TONES[c.tone] || "var(--accent)" } }, /* @__PURE__ */ React.createElement("span", { className: "cg-label", style: { color: CARD_TONES[c.tone] || "var(--accent)" } }, c.label), c.what && /* @__PURE__ */ React.createElement("span", { className: "cg-what" }, c.what), c.why && /* @__PURE__ */ React.createElement("span", { className: "cg-why" }, c.why)))));
};
const NamedDiagram = ({ data }) => {
  const C = data && data.component && window[data.component];
  if (!C) return null;
  return /* @__PURE__ */ React.createElement(VizFrame, { title: data.title, note: data.note, source: data.source }, /* @__PURE__ */ React.createElement(C, null));
};
const VIZ_CHARTS = {
  area: AreaChart,
  benchmark: BenchmarkChart,
  share: ShareBars,
  gateflow: GateFlow,
  cards: CardGrid,
  diagram: NamedDiagram
};
const VizChart = ({ data }) => {
  const C = data && VIZ_CHARTS[data.kind];
  return C ? /* @__PURE__ */ React.createElement(C, { data }) : null;
};
window.DiagramExplorer = DiagramExplorer;
window.DgxBox = DgxBox;
window.AreaChart = AreaChart;
window.BenchmarkChart = BenchmarkChart;
window.ShareBars = ShareBars;
window.GateFlow = GateFlow;
window.CardGrid = CardGrid;
window.NamedDiagram = NamedDiagram;
window.VizChart = VizChart;
